### ISSUE TITLE
UI Created

### ISSUE THREAD

**Issue by TheAurelian** [djblooky/candle-light#110]
UI created
UI Implemented

- [x] Title
- [x] Credit
- [x] Pause

Dwight: Hey if you wanna make mock ups of the UI **_Flow_** and provide the art assets for things like buttons and backgrounds and such I can hook them up and make them actually work as buttons. Once you have most of it done check with me and I'll make sure you have all the assets necessary :)

**Comment by VocaloidZero** [comment]
![candletitle](https://user-images.githubusercontent.com/33336209/111539683-898a4c00-8744-11eb-86e6-e2c960c21782.png)
![Button3](https://user-images.githubusercontent.com/33336209/111539685-8a22e280-8744-11eb-8486-d130d4c8b119.png)
![Button2](https://user-images.githubusercontent.com/33336209/111539686-8a22e280-8744-11eb-8b7a-2d91a485795e.png)
![Button1](https://user-images.githubusercontent.com/33336209/111539688-8abb7900-8744-11eb-9407-a77cd75ae2a1.png)
![CreditPaper](https://user-images.githubusercontent.com/33336209/111539689-8abb7900-8744-11eb-88d5-38f1856e118c.png)

**Comment by VocaloidZero** [comment]
![darkBGWhite](https://user-images.githubusercontent.com/33336209/112415017-7ace0700-8cf9-11eb-857f-cfca8675b1cc.png)
![darkBG](https://user-images.githubusercontent.com/33336209/112415020-7b669d80-8cf9-11eb-9a9c-a4e294e37330.png)
