### ISSUE TITLE
Icons for hover over objects

### ISSUE THREAD

**Issue by djblooky** [djblooky/candle-light#139]
- [x] Hand grab
- [x] Lock
- [x] Unlock
- [x] Burn?
- [x] Examine (Eye or magnifying glass)

Start with sketches, get feedback and then move to 2D assets

**Comment by VocaloidZero** [comment]
![Grab](https://user-images.githubusercontent.com/33336209/113074980-151ac880-919a-11eb-95ed-0d96a8b6e083.png)
![HandHover](https://user-images.githubusercontent.com/33336209/113074982-15b35f00-919a-11eb-93d6-322cfcecf267.png)
![Burn](https://user-images.githubusercontent.com/33336209/113074984-164bf580-919a-11eb-9432-a8296c4113af.png)
![Unlock](https://user-images.githubusercontent.com/33336209/113074987-16e48c00-919a-11eb-817f-1bca9acf09a1.png)
![Lock](https://user-images.githubusercontent.com/33336209/113074989-1815b900-919a-11eb-8021-be2b23a0571e.png)
![Inspect](https://user-images.githubusercontent.com/33336209/113074992-18ae4f80-919a-11eb-83a4-c37919091750.png)
![Observe](https://user-images.githubusercontent.com/33336209/113074994-1946e600-919a-11eb-8168-330f7cde9a68.png)
