### ISSUE TITLE
Props

### ISSUE THREAD

**Issue by TheAurelian** [djblooky/candle-light#41]
- [x] Single chair variation
- [x] Double chair
- [x] Lounge Chair
- [x] Vellum (Square or rectangular piece of paper for artwork) + Rolled Up version
- [x] Vase?
- [x] Couch (Do 1st)
- [x] Rug (2 versions?) (Do 1st)
- [x] Corner Table
- [x] Circular Table
- [x] Phonograph
- [x] Globe that opens
- [x] Grandfather Clock (Do 1st)
- [x] Door handle (Do 1st)

**Comment by VocaloidZero** [comment]
Pictures for the frames
[Oldtimepics.zip](https://github.com/djblooky/candle-light/files/6093050/Oldtimepics.zip)
