### ISSUE TITLE
Sketch UI Screens

### ISSUE THREAD

**Issue by TheAurelian** [djblooky/candle-light#84]
- [x] Title screen
- [x] Pause menu
- [x] Credits
- [ ] Quit game

**Comment by VocaloidZero** [comment]
![image](https://user-images.githubusercontent.com/33336209/110838725-cea80d00-8270-11eb-8168-ec01c3eb92f2.png)
![image](https://user-images.githubusercontent.com/33336209/110838764-d8ca0b80-8270-11eb-93ba-f4417e333e0a.png)
![Uploading image.png…]()

**Comment by VocaloidZero** [comment]
![image](https://user-images.githubusercontent.com/33336209/110838872-f7c89d80-8270-11eb-9bfa-b7b0029a4d40.png)
